In [1]:
import camelot
import pandas as pd
import bs4 as BeautifulSoup
import requests
import json

c:\Users\Tan_S\AppData\Local\Programs\Python\Python311\Lib\site-packages\pypdf\_crypt_providers\_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4

In [2]:
overall_data = {
    'Station Name': [],
    'Latitude': [],
    'Longitude': [],
    'Station ID': []
}
print(overall_data)
all_station_data = pd.DataFrame(overall_data)

{'Station Name': [], 'Latitude': [], 'Longitude': [], 'Station ID': []}

In [3]:
## getting station id from data.gov.sg api
url_list = [
    "https://api-open.data.gov.sg/v2/real-time/api/air-temperature",
    "https://api-open.data.gov.sg/v2/real-time/api/rainfall",
    "https://api-open.data.gov.sg/v2/real-time/api/wind-direction",
    "https://api-open.data.gov.sg/v2/real-time/api/wind-speed",
    "https://api-open.data.gov.sg/v2/real-time/api/relative-humidity"]

responses = [requests.get(url) for url in url_list]
json_data = [response.json() for response in responses]

for i in range(len(url_list)):
    data = json_data[i]
    for station in data['data']['stations']:
        if station['id'] not in overall_data['Station ID']:
            name = station['name']
            id = station['id']
            lat = station['location']['latitude']
            long = station['location']['longitude']

            overall_data['Station Name'].append(name)
            overall_data['Latitude'].append(lat)
            overall_data['Longitude'].append(long)
            overall_data['Station ID'].append(id)
        else:
            continue

In [4]:
## sanity check: number of stations collected in overall_data
len(overall_data['Station Name'])

60

In [5]:
all_station_data = pd.DataFrame(overall_data)

In [6]:
all_station_data

                   Station Name  Latitude  Longitude Station ID
0           Ang Mo Kio Avenue 5   1.37640  103.84920       S109
1                    Pulau Ubin   1.41680  103.96730       S106
2                   Banyan Road   1.25600  103.67900       S117
3            East Coast Parkway   1.31350  103.96250       S107
4           Tuas South Avenue 3   1.29377  103.61843       S115
5              Semakau Landfill   1.18900  103.76800       S102
6                       Sentosa   1.25000  103.82790        S60
7                 Clementi Road   1.33370  103.77680        S50
8                Nanyang Avenue   1.34583  103.68166        S44
9                Kim Chuan Road   1.33990  103.88780        S43
10      Upper Changi Road North   1.36780  103.98260        S24
11                  Scotts Road   1.31055  103.83650       S111
12                   Paya Lebar   1.35240  103.90070        S06
13            Yio Chu Kang Road   1.37999  103.87643       S219
14         Ang Mo Kio Avenue 10   1.36019  103.85335       S216
15             Bishan Street 13   1.35041  103.85526       S217
16                  Tanjong Rhu   1.29911  103.88289       S214
17         Geylang East Central   1.32785  103.88899       S215
18              Coronation Walk   1.32427  103.80970       S213
19              Punggol Central   1.40290  103.90920        S81
20             Mandai Lake Road   1.40440  103.78962        S40
21                 Simei Avenue   1.34370  103.94440        S84
22              Toa Payoh North   1.34270  103.84820        S88
23             Hougang Avenue 1   1.35691  103.89088       S221
24               Henderson Road   1.28987  103.82364       S222
25           Upper Thomson Road   1.37010  103.82710        S08
26                  Lornie Road   1.34150  103.83340        S07
27             Compassvale Lane   1.38666  103.89797       S220
28            Changi East Close   1.31360  104.00317       S208
29                Pasir Panjang   1.29164  103.77020       S203
30                Clementi Park   1.32311  103.76714       S201
31             Bukit Timah Road   1.31910  103.81910        S90
32       South Buona Vista Road   1.28410  103.78860        S92
33             Yishun Ring Road   1.42111  103.84472       S209
34          Pasir Ris Street 51   1.36620  103.95280        S94
35                  Kranji Road   1.42918  103.75711       S211
36               Nicoll Highway   1.30105  103.86660       S119
37           Marine Parade Road   1.30648  103.91040       S113
38           Bukit Panjang Road   1.38240  103.76030        S64
39                   Kranji Way   1.43870  103.73630        S66
40  Upper Peirce Reservoir Park   1.37000  103.80500        S69
41                  Towner Road   1.32140  103.85770       S123
42         Marina Gardens Drive   1.27990  103.87030       S108
43        Jurong West Street 42   1.35167  103.72195       S229
44       Seletar Aerospace View   1.41284  103.86922       S900
45           Woodlands Drive 62   1.43944  103.80389       S227
46        Jurong West Street 73   1.34703  103.70073       S228
47                   Malan Road   1.27472  103.80389       S226
48               Margaret Drive   1.29984  103.80264       S223
49            Airport Boulevard   1.34392  103.98409       S224
50              Kent Ridge Road   1.29230  103.78150        S71
51             Jurong Pier Road   1.30810  103.71000        S33
52               Alexandra Road   1.29370  103.81250        S77
53            Old Toh Tuck Road   1.33290  103.75560        S35
54                Somerset Road   1.30040  103.83720        S79
55                   Poole Road   1.30703  103.89067        S78
56            Lim Chu Kang Road   1.43854  103.70131       S112
57              West Coast Road   1.30167  103.76444       S230
58           Woodlands Avenue 9   1.44387  103.78538       S104
59       Old Choa Chu Kang Road   1.37288  103.72244       S121

In [7]:
########################################################################################
# do not change
lat_min, lat_max = 1.15, 1.47
lon_min, lon_max = 103.56, 104.14   
########################################################################################

########################################################################################
# do not change
scale_x = 217 / 853
scale_y = 120 / 479
########################################################################################


def latlon_to_xy(lat, lon, lat_min, lat_max, lon_min, lon_max, width, height):
    """
    Convert latitude and longitude to pixel coordinates on the radar image grid.

    Args:
        lat, lon : float
        lat_min, lat_max, lon_min, lon_max : float
            Bounding box of the radar coverage.
        width, height : int
            Dimensions of the radar image (e.g. 217x120).

    Returns:
        (x, y) pixel coordinates (integers)
    """

    # normalize longitude to horizontal position
    x = (lon - lon_min) / (lon_max - lon_min) * (width - 1)
    # normalize latitude to vertical position (note inversion: north is top)
    y = (lat_max - lat) / (lat_max - lat_min) * (height - 1)

    return int(round(x)), int(round(y))

def basemap_to_radar(X, Y):
    x = X * scale_x
    y = Y * scale_y
    return int(round(x)), int(round(y))

all_station_data['coord_basemap'] = all_station_data.apply(lambda row : latlon_to_xy(row['Latitude'],row['Longitude'],lat_min, lat_max, lon_min, lon_max,853,479),axis = 1)

all_station_data.rename(columns={'Station Name':'station_name','Latitude':'latitude','Longitude':'longitude','Station ID':'station_id'},inplace = True)


all_station_data["coord"] = all_station_data["coord_basemap"].apply(lambda xy: basemap_to_radar(xy[0], xy[1]))

In [8]:
all_station_data

,station_name,latitude,longitude,station_id,coord_basemap,coord
0,Ang Mo Kio Avenue 5,1.37640,103.84920,S109,"(425, 140)","(108, 35)"
1,Pulau Ubin,1.41680,103.96730,S106,"(598, 79)","(152, 20)"
2,Banyan Road,1.25600,103.67900,S117,"(175, 320)","(45, 80)"
3,East Coast Parkway,1.31350,103.96250,S107,"(591, 234)","(150, 59)"
4,Tuas South Avenue 3,1.29377,103.61843,S115,"(86, 263)","(22, 66)"
5,Semakau Landfill,1.18900,103.76800,S102,"(306, 420)","(78, 105)"
6,Sentosa,1.25000,103.82790,S60,"(394, 329)","(100, 82)"
7,Clementi Road,1.33370,103.77680,S50,"(318, 204)","(81, 51)"
8,Nanyang Avenue,1.34583,103.68166,S44,"(179, 185)","(46, 46)"
9,Kim Chuan Road,1.33990,103.88780,S43,"(482, 194)","(123, 49)"
10,Upper Changi Road North,1.36780,103.98260,S24,"(621, 153)","(158, 38)"
11,Scotts Road,1.31055,103.83650,S111,"(406, 238)","(103, 60)"
12,Paya Lebar,1.35240,103.90070,S06,"(500, 176)","(127, 44)"
13,Yio Chu Kang Road,1.37999,103.87643,S219,"(465, 134)","(118, 34)"
14,Ang Mo Kio Avenue 10,1.36019,103.85335,S216,"(431, 164)","(110, 41)"
15,Bishan Street 13,1.35041,103.85526,S217,"(434, 179)","(110, 45)"
16,Tanjong Rhu,1.29911,103.88289,S214,"(474, 255)","(121, 64)"
17,Geylang East Central,1.32785,103.88899,S215,"(483, 212)","(123, 53)"
18,Coronation Walk,1.32427,103.80970,S213,"(367, 218)","(93, 55)"
19,Punggol Central,1.40290,103.90920,S81,"(513, 100)","(131, 25)"
20,Mandai Lake Road,1.40440,103.78962,S40,"(337, 98)","(86, 25)"
21,Simei Avenue,1.34370,103.94440,S84,"(565, 189)","(144, 47)"
22,Toa Payoh North,1.34270,103.84820,S88,"(423, 190)","(108, 48)"
23,Hougang Avenue 1,1.35691,103.89088,S221,"(486, 169)","(124, 42)"
24,Henderson Road,1.28987,103.82364,S222,"(387, 269)","(98, 67)"
25,Upper Thomson Road,1.37010,103.82710,S08,"(392, 149)","(100, 37)"
26,Lornie Road,1.34150,103.83340,S07,"(402, 192)","(102, 48)"
27,Compassvale Lane,1.38666,103.89797,S220,"(496, 124)","(126, 31)"
28,Changi East Close,1.31360,104.00317,S208,"(651, 234)","(166, 59)"
29,Pasir Panjang,1.29164,103.77020,S203,"(309, 266)","(79, 67)"
30,Clementi Park,1.32311,103.76714,S201,"(304, 219)","(77, 55)"
31,Bukit Timah Road,1.31910,103.81910,S90,"(381, 225)","(97, 56)"
32,South Buona Vista Road,1.28410,103.78860,S92,"(336, 278)","(85, 70)"
33,Yishun Ring Road,1.42111,103.84472,S209,"(418, 73)","(106, 18)"
34,Pasir Ris Street 51,1.36620,103.95280,S94,"(577, 155)","(147, 39)"
35,Kranji Road,1.42918,103.75711,S211,"(290, 61)","(74, 15)"
36,Nicoll Highway,1.30105,103.86660,S119,"(450, 252)","(114, 63)"
37,Marine Parade Road,1.30648,103.91040,S113,"(515, 244)","(131, 61)"
38,Bukit Panjang Road,1.38240,103.76030,S64,"(294, 131)","(75, 33)"
39,Kranji Way,1.43870,103.73630,S66,"(259, 47)","(66, 12)"
40,Upper Peirce Reservoir Park,1.37000,103.80500,S69,"(360, 149)","(92, 37)"
41,Towner Road,1.32140,103.85770,S123,"(437, 222)","(111, 56)"
42,Marina Gardens Drive,1.27990,103.87030,S108,"(456, 284)","(116, 71)"
43,Jurong West Street 42,1.35167,103.72195,S229,"(238, 177)","(61, 44)"
44,Seletar Aerospace View,1.41284,103.86922,S900,"(454, 85)","(115, 21)"
45,Woodlands Drive 62,1.43944,103.80389,S227,"(358, 46)","(91, 12)"
46,Jurong West Street 73,1.34703,103.70073,S228,"(207, 184)","(53, 46)"
47,Malan Road,1.27472,103.80389,S226,"(358, 292)","(91, 73)"
48,Margaret Drive,1.29984,103.80264,S223,"(356, 254)","(91, 64)"
49,Airport Boulevard,1.34392,103.98409,S224,"(623, 188)","(158, 47)"
50,Kent Ridge Road,1.29230,103.78150,S71,"(325, 265)","(83, 66)"
51,Jurong Pier Road,1.30810,103.71000,S33,"(220, 242)","(56, 61)"
52,Alexandra Road,1.29370,103.81250,S77,"(371, 263)","(94, 66)"
53,Old Toh Tuck Road,1.33290,103.75560,S35,"(287, 205)","(73, 51)"
54,Somerset Road,1.30040,103.83720,S79,"(407, 253)","(104, 63)"
55,Poole Road,1.30703,103.89067,S78,"(486, 243)","(124, 61)"
56,Lim Chu Kang Road,1.43854,103.70131,S112,"(208, 47)","(53, 12)"
57,West Coast Road,1.30167,103.76444,S230,"(300, 251)","(76, 63)"
58,Woodlands Avenue 9,1.44387,103.78538,S104,"(331, 39)","(84, 10)"
59,Old Choa Chu Kang Road,1.37288,103.72244,S121,"(239, 145)","(61, 36)"